replicaCount: 1
version: "1.0.7"

targetPort: 8001

service:
  db: task-mongodb

secrets:
  ginMode: release
  userBackendApiUrl: 
  allowOrigins: http://localhost:3000,http://localhost:3001

global:
  namespace: srf-savetask
  volume:
    path: /mnt/srf-savetask
    storageClassName: srf-savetask-storage
  dbVolume:
    pv: task-api-pv
    pvc: task-api-pvc
    size: 5Gi
    values:
      - minikube
  # backup:
  #   # everyday at 10 am
  #   full:
  #     schedule: "0 10 * * *"
  #   # hourly
  #   incremental:
  #     schedule: "0 * * * *"
  #   volume:
  #     name: task-api-backup
  #     pv: task-api-backup-pv
  #     pvc: task-api-backup-pvc
  #     size: 5Gi
  #     values:
  #       - minikube

image:
  repository: registry.shereif.com/srf-savetask/task-api
  tag: latest

imagePullSecrets:
  name: regcred

task-mongodb:
  replicaCount: 1

  database:
    name: task-db

  dbVolume:
    name: mongodb-data
    path: /data/db

  # use override to set the username and password

  secrets:
    username: task-api-mongodb-admin
    password: someweirdpass

  image:
    name: mongo
    tag: latest

  targetPort: 27017