apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
data:

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
data:
  jwtSecret: {{ .Values.secrets.jwtSecret | b64enc }}
  jwtIssuer: {{ .Values.secrets.jwtIssuer | b64enc }}
  jwtAudience: {{ .Values.secrets.jwtAudience | b64enc }}
  jwtExpire: {{ .Values.secrets.jwtExpire | toString | b64enc }}
  passPepper: {{ .Values.secrets.passPepper | b64enc }}
