apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        chart: {{ .Chart.Name }}
      annotations:
        version: {{ .Values.version }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.targetPort }}
          env:
            - name: GIN_MODE
              value: {{ .Values.secrets.ginMode }}
            - name: PORT
              value: {{ .Values.targetPort | quote }}
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.service.db }}-config
                  key: db
            - name: DB_HOST
              value: {{ .Release.Name }}-{{ .Values.service.db }}
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.service.db }}-config
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.service.db }}-secrets
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.service.db }}-secrets
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: jwtSecret
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: jwtIssuer
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: jwtAudience
            - name: JWT_EXPIRE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: jwtExpire
            - name: PASS_PEPPER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: passPepper
            - name: ALLOW_ORIGINS
              value: {{ .Values.secrets.allowOrigins }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.targetPort }}
      targetPort: {{ .Values.targetPort }}