package common

const (
	MONGO_DB_HOST = "MONGO_DB_HOST"
	MONGO_DB_PORT = "MONGO_DB_PORT"
	MONGO_DB_USER = "MONGO_DB_USER"
	MONGO_DB_PASS = "MONGO_DB_PASS"
	MONGO_DB_NAME = "MONGO_DB_NAME"

	GIN_MODE = "GIN_MODE"
	DEBUG    = "debug"
	RELEASE  = "release"

	ADMIN_PASS_MUST_REMOVE = "ADMIN_PASS_MUST_REMOVE"
)
