apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
data:
  port: {{ .Values.targetPort | quote }}
  db: {{ .Values.database.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
data:
  username: {{ .Values.secrets.username | b64enc }}
  password: {{ .Values.secrets.password | b64enc }}
