version: "3.7"

services:
  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    restart: always
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - savetask-mongoDBVolume:/data/db
volumes:
  savetask-mongoDBVolume:
