replicaCount: 1
version: "1.0.5"

image:
  repository: registry.shereif.com/srf-savetask/task-nextjs-fe
  tag: "latest"
  pullSecrets:
    name: regcred
  
secrets:
  NEXT_PUBLIC_TASK_API_URL: https://savetask.shereif-test.com/api
  NEXT_PUBLIC_TASK_BACKEND_URL: http://taskapirelease-task-api-helm:8001/api
  NEXT_PUBLIC_USER_API_URL: https://savetask.shereif-test.com/api
  NEXT_PUBLIC_USER_BACKEND_URL: http://userapirelease-user-api-helm:8002/api

service:
  port: 3001
  targetPort: 3000